language: node_js
node_js:
 - "0.10"
services:
 - mongodb
deploy:
 provider: heroku
 api_key: "c3d25faf-e17f-4b3d-b297-3a6f164d707a"
 app:
  master: buet73-staging
  production: buet73
notifications:
 email:
  - buet73@asifchoudhury.com
before_install:
 - chmod +x ./bin/ci/install_neo4j.sh
 - ./bin/ci/install_neo4j.sh
 - npm install -g grunt-cli
script: "npm test && grunt test-functional"
